### ISSUE TITLE
Initialization bug when running with other models

### ISSUE THREAD

**Issue by Murilodsv** [Murilodsv/dssat-csm-os#3]
Following up Cheryl's email:

---

Hi, Murilo;
I am running lots of tests on the new code that we got at the DSSAT sprint last week. **_I uncovered a problem with the SAMUCA model when it is run after one of the other models. It seems that the cultivar coefficients are not read unless the SAMUCA model is the first model in a batch._** For example, try running the attached batch file. When the Canegro experiment is run first, the model bombs because Task 1 is not done and the genetic coefficients are not read in. If the order is reversed and the SAMUCA experiment is first (as is the normal alphabetical case) everything is fine.

(command line from the data directory: <path+model> B Sugarcane.v47)

Can you check it out? If it is just the one call, I could move it to Task 2, but I think it might need more careful scrutiny.

---

[Sugarcane.zip](https://github.com/Murilodsv/dssat-csm-os/files/5005985/Sugarcane.zip)

**Comment by Murilodsv** [comment]
There was a call missing to initialize flags for reading species file.
This is now fixed in: https://github.com/Murilodsv/dssat-csm-os/commit/cf9b9757aa9fe3af68573d360e8adf4569e90545

Thanks, @chporter!

I had also tested multiple runs as suggested by @GerritHoogenboom. 
It appears that the initialization is now OK:

- batch file: [DSSBatch.zip](https://github.com/Murilodsv/dssat-csm-os/files/5006589/DSSBatch.zip)

![image](https://user-images.githubusercontent.com/16140093/89027424-64b2a700-d322-11ea-890a-3d646d3dea49.png)

![image](https://user-images.githubusercontent.com/16140093/89027519-8e6bce00-d322-11ea-9d8a-a7cf0dc162c5.png)

**Comment by chporter** [comment]
Works great! Thanks!
